run:
  timeout: 5m

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 14
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: 60
    statements: 40
  forbidigo:
    forbid:
      - ^print(ln)?$
      - ^fmt\.Print(f|ln)?$
      - ^spew\.Print(f|ln)?$
      - ^spew\.Dump$
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/instana/testify"
            desc: not allowed
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
  godox:
    keywords:
      - FIXME

linters:
  enable-all: true
  disable:
    - exportloopref # deprecated
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - cyclop
    - bodyclose
    - prealloc
    - lll
    - mnd
    - wsl
    - nlreturn
    - err113
    - wrapcheck
    - testpackage
    - tparallel
    - paralleltest
    - exhaustive
    - exhaustruct
    - makezero
    - noctx
    - varnamelen

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude: []
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
    - path: goproxy/client_test.go
      linters:
        - forbidigo
    - path: metago/metago.go
      text: cyclomatic complexity 15 of func `parseMetaGo` is high
    - linters:
        - usestdlibvars
      text: '"100" can be replaced by http.StatusContinue'
    - path: goenv/names.go
      linters:
        - revive
        - stylecheck
      text: "use ALL_CAPS in Go names; use CamelCase"
