run:
  timeout: 5m
  skip-files: []

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 14
  maligned:
    suggest-new: true
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: 60
    statements: 40
  forbidigo:
    forbid:
      - ^print(ln)?$
      - ^fmt\.Print(f|ln)?$
      - ^spew\.Print(f|ln)?$
      - ^spew\.Dump$
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/instana/testify"
            desc: not allowed
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
  godox:
    keywords:
      - FIXME

linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - exhaustivestruct # deprecated
    - golint # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - nosnakecase # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - cyclop # duplicate of gocyclo
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - execinquery # not relevant (SQL)
    - cyclop
    - bodyclose
    - prealloc
    - lll
    - gomnd
    - wsl
    - nlreturn
    - goerr113
    - wrapcheck
    - testpackage
    - tparallel
    - paralleltest
    - exhaustive
    - exhaustruct
    - makezero
    - ifshort
    - noctx
    - varnamelen

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude: []
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
    - path: goproxy/client_test.go
      linters:
        - forbidigo
    - path: metago/metago.go
      text: cyclomatic complexity 15 of func `parseMetaGo` is high
